---
title: "3-1. Consolidate fasta file"
author: "Yoichiro Sugimoto"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   github_document:
     toc: yes
     toc_depth: 2
---

Searching the entire proteome with MaxQuant while allowing for many PTMs is too time consuming. Here, fasta files containing the proteins identified by the primary search are generated and used for the search.

# Environment setup

```{r renv_set, warning=FALSE}

# renv::init(
#           "/fast/AG_Sugimoto/home/users/yoichiro/projects/20241111_PTMs_in_lysine_rich_domains/R"
#       )

project.dir <-
  file.path(
    "/fast/AG_Sugimoto/home/users/yoichiro/projects/20241111_PTMs_in_lysine_rich_domains"
  )

# renv::snapshot(file.path(project.dir, "R"))

renv::restore(file.path(project.dir, "R"))

```


```{r set parameters}

temp <-
  sapply(list.files(
    file.path(project.dir, "R/functions"),
    pattern = "*.R",
    full.names = TRUE
  ),
  source)

# install.packages("/fast/AG_Sugimoto/home/users/yoichiro/projects/ptm.stoichiometry", repos = NULL, type = "source")
library("readxl")

p3.res.dir <- file.path(project.dir,
                        "results",
                        "p3-ptm-interplay")

consolidated.fasta.dir <- file.path(
  p3.res.dir,
  "consolidated_fasta"
)

create.dirs(c(p3.res.dir, consolidated.fasta.dir))


```

# Import basic data

```{r import_basic_data}

data.dir <- file.path(project.dir, "data")

proteinGroup.dir <- file.path(data.dir, "MQ_DI_output/PNAS2022/proteinGroups")

original_fasta <- file.path("/fast/AG_Sugimoto/reference/uniprot/human/UP000005640_9606.fasta")

```


# Consolidate fasta files


```{r consolidate_fasta}

library("ptm.stoichiometry")

consolidate_fastas <- function(input_protein_group, original_fasta, consolidated.fasta.dir){
  
  protein_exp <- preprocess_protein_expression_data(input_protein_group)
  protein_exp <- protein_exp[razor_unique_peptides > 0]
  
  output_fasta <- gsub("_proteinGroups.txt", ".fasta", basename(input_protein_group))
  
  consolidated_fasta <- file.path(consolidated.fasta.dir, output_fasta)
  
  print(paste0("Proteins to be included in ", output_fasta, ": ", nrow(protein_exp)))
  
  selected_fasta_headers <- protein_exp[, unlist(split_fasta_headers)]
  
  temp <- consolidate_fasta(original_fasta, consolidated_fasta, selected_fasta_headers)
}

temp <- lapply(
  list.files(proteinGroup.dir, full.names = TRUE),
  consolidate_fastas,
  original_fasta = original_fasta,
  consolidated.fasta.dir = consolidated.fasta.dir
)

```


# Session information

```{r sessionInfo}

sessioninfo::session_info()

```
