---
title: "2-1_1. PSM_PTM_comparisons"
author: "Yoichiro Sugimoto and Pallavi Kesavan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   github_document:
     toc: yes
     toc_depth: 2
---

# Overview

# This script calculates the stiochiomtery using MaxQuant data  

# Environment setup

```{r setup_environment}

## Initialize renv (first time only) - re-installed 24.09.2025
# Creates project specific library and renv.lock file. 
# Use 'renv::init(filepath)' to create project library
# renv::init(
#        "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains/R"
#    )

# Define project directory - contains the R scripts, data and result folders
project.dir <-
  file.path(
    "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains"
  )

# renv::snapshot(file.path(project.dir, "R"))

#renv::restore completed 24.09.2025
#renv::restore(file.path(project.dir, "R"))

```

# 2.1.1.1 Install,load essential functions and libraries

```{r load_essential_functions_current_session}

## Load all R scripts from the 'functions' folder into the current session
P2_functions <- sapply(list.files(file.path(project.dir, "R/functions"), pattern="*.R", full.names = TRUE), source)

## Install private package 
# Install ptm.stiochiometry package
#install.packages("/fast/AG_Sugimoto/home/users/pallavi/projects/ptm.stoichiometry", repos = NULL, type = "source")

# Load Libraries - ptm.stiochiometry and readxl
library(ptm.stoichiometry)
library("readxl")

```

```{r data_directories}

# Define path to data directory
data.dir <- file.path(project.dir, "data")
results.dir <- file.path(project.dir, "results")

```

# 2.1.1.2 Import human protein reference data 

```{r import_data, warning=FALSE}

# Import human protein reference data from specified file path 
ref_protein_data <- import_reference_fasta(file.path
                                           ("/fast/AG_Sugimoto/reference/uniprot/human", 
                                             "UP000005640_9606.fasta")) 

all.protein.bs <- Biostrings::readAAStringSet(
  file.path(
    "/fast/AG_Sugimoto/reference/uniprot/human",
    "UP000005640_9606.fasta"
  )
)

```


# 2.1.1.3 Comparison - PNAS2022 versus new workflow for PSM coverage and PTM stoichiometry

```{r define_functions}

# Define function - 'read_stoic_data'
read_stoic_data <- function(prefix, pre_prefix, post_fix = "", dir_path){
  # Read csv file with defined file path,  
  dt <- fread(file.path(dir_path, paste0(pre_prefix, prefix, "PTM_stoichiometry", post_fix, ".csv"))) 
  dt[, condition := gsub("_$", "", prefix)] # Removes '_' at the end of the prefix and creates a new column called condition
  return(dt)
}

```


```{r comparison_PNAS2022_PTM_PSM}

pnas2022.stoic.dt <- fread(file.path(data.dir, "PNAS2022/long_K_stoichiometry_data.csv"))

setnames(
  pnas2022.stoic.dt, 
  old = c("uniprot_id", "position", "residue", "oxK_ratio", "data_source"), 
  new = c("protein_accession", "aa_pos", "aa", "stoichiometry", "sample_name")
)

pnas2022.stoic.dt[, `:=`(
  sum_psm_mapped = total_n_feature_K + total_n_feature_oxK
)]

pnas2022.stoic.dt <- merge(
  ref_protein_data[, .(protein_accession, gene_name)],
  pnas2022.stoic.dt,
  by = "protein_accession"
)

pnas2022.stoic.dt[, `:=`(
  accession_position = paste0(protein_accession, "_", aa_pos),
  ptm = "[Oxidation (K)]",
  sample_name = gsub("HeLa_", "HeLa", sample_name) %>%
    {gsub("HeLaJMJD6FLAG", "HeLaWT_JMJD6FLAG", .)}
)]


#---------------
# PNAS2022 - WT
#---------------

# PNAS2022 - BRD4 WT -PSM
PNAS2022_PSM_WT <-plot_psm_coverage(
  pnas2022.stoic.dt[sample_name == "HeLaWT_JQ1"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)

PNAS2022_PSM_WT <- PNAS2022_PSM_WT$coverage_plot_g

# PNAS2022 - BRD4 WT -PTM
PNAS2022_PTM_WT <- plot_ptm_stoichiometry(
  pnas2022.stoic.dt[sample_name == "HeLaWT_JQ1"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)

#--------------------
# PNAS2022 - JMJD6KO
#--------------------

# PNAS2022 - BRD4 JMJD6KO -PSM
PNAS2022_PSM_JMJD6KO <- plot_psm_coverage(
  pnas2022.stoic.dt[sample_name == "HeLaJMJD6KO_JQ1"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)

PNAS2022_PSM_JMJD6KO <- PNAS2022_PSM_JMJD6KO$coverage_plot_g

# PNAS2022 - BRD4 JMJD6KO - PTM 
PNAS2022_PTM_JMJD6KO <- plot_ptm_stoichiometry(
  pnas2022.stoic.dt[sample_name == "HeLaJMJD6KO_JQ1"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)


# Combine PSM and PTM plot together using patchwork
# WT
#PNAS2022_PSM_WT/PNAS2022_PTM_WT

# JMJD6KO
#PNAS2022_PSM_JMJD6KO/PNAS2022_PTM_JMJD6KO

# Load library 
library(ggplot2)
library(ggpubr)

# Combine PSM and PTM plot together using ggarrange
# WT
ggarrange(
  PNAS2022_PSM_WT, PNAS2022_PTM_WT,
  ncol = 1, nrow = 2,
  align = "hv", 
  legend = "none"
)

# JMJD6KO
ggarrange(
  PNAS2022_PSM_JMJD6KO, PNAS2022_PTM_JMJD6KO,
  ncol = 1, nrow = 2,
  align = "hv", 
  legend = "none"
)

```

```{r comparison_MQ_Std_PSM_PTM}

# Load sample run info data (MQ standard)
MQ_Std_run_info <- read_excel(
  file.path(project.dir, "data/analysis_setting/PXD031221_sample_matrix.xlsx"),
  sheet = "MQ_standard" 
) %>% data.table

# Add a new column 'sample_id' that assigns a unique sequential number to each 
#row (1:N), where N is the total number of rows in the data.table
MQ_Std_run_info[, sample_id := 1:.N]

## Read stoichiometry data for MQ_DI
MQ_Std_stoic_dt <- lapply(
  MQ_Std_run_info[, prefix],
  read_stoic_data,
  pre_prefix = "", 
  post_fix = "",
  dir_path = file.path(results.dir, "p2-analysis-setting", "MQ_Std_MSMS")
) %>% rbindlist

# MQ_DI - BRD4 WT - PTM 
MQ_PTM_WT <- plot_ptm_stoichiometry(
  MQ_Std_stoic_dt[sample_name == "JQ1_HeLaWT_derivatised"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)

# MQ_DI - BRD4 WT - PSM 
MQ_PSM_WT <- plot_psm_coverage(
  MQ_Std_stoic_dt[sample_name == "JQ1_HeLaWT_derivatised"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)

MQ_PSM_WT <- MQ_PSM_WT$coverage_plot_g

# Combine PSM and PTM plot together using ggarrange
# WT
ggarrange(
  MQ_PSM_WT, MQ_PTM_WT,
  ncol = 1, nrow = 2,
  align = "hv", 
  legend = "none"
)


# MQ_DI - BRD4 JMJD6KO - PSM 
MQ_PSM_JMJD6KO <-plot_psm_coverage(
  MQ_Std_stoic_dt[sample_name == "JQ1_HeLaJMJD6KO_derivatised"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)

MQ_PSM_JMJD6KO <- MQ_PSM_JMJD6KO$coverage_plot_g

# MQ_DI - BRD4 JMJD6KO - PTM
MQ_PTM_JMJD6KO <- plot_ptm_stoichiometry(
  MQ_Std_stoic_dt[sample_name == "JQ1_HeLaJMJD6KO_derivatised"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)

# Combine PSM and PTM plot together using ggarrange
# JMJD6KO
ggarrange(
  MQ_PSM_JMJD6KO, MQ_PTM_JMJD6KO,
  ncol = 1, nrow = 2,
  align = "hv", 
  legend = "none"
)


```

# 2.1.1.4 Comparing PSM coverage between m2, m5, and m7 miscleavages

```{r MQ_Std_PSM_miscleavages}

## MQ_DI PSM coverage according to miscleavages (m2, m5, m7)

# m2
MQ_PSM_WT <- plot_psm_coverage(
  MQ_Std_stoic_dt[sample_name == "JQ1_HeLaWT_derivatised" & condition == "data-A_trp_m2_v2_def"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA) 
MQ_PSM_WT$coverage_plot_g + coord_cartesian(ylim = c(0, 350)) +
    labs(title = "BRD4 PSM miscleavages m2")

# m5
MQ_PSM_WT <- plot_psm_coverage(
  MQ_Std_stoic_dt[sample_name == "JQ1_HeLaWT_derivatised" & condition == "data-A_trp_m5_v5_def"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)
MQ_PSM_WT$coverage_plot_g + coord_cartesian(ylim = c(0, 350))

# m7
MQ_PSM_WT <- plot_psm_coverage(
  MQ_Std_stoic_dt[sample_name == "JQ1_HeLaWT_derivatised" & condition == "data-A_trp_m7_v7_def"], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA)
MQ_PSM_WT$coverage_plot_g + coord_cartesian(ylim = c(0, 350))
MQ_PSM_WT <- MQ_PSM_WT$coverage_plot_g

```


# Session information

```{r sessionInfo}

sessioninfo::session_info()

```

