---
title: "2-1. Calculate PTM stoichiometry"
author: "Yoichiro Sugimoto and Pallavi Kesavan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   github_document:
     toc: yes
     toc_depth: 2
---

# Overview

# This script calculates the stiochiomtery using MaxQuant data  

# Environment setup

```{r setup_environment}

## Initialize renv (first time only) - re-installed 24.09.2025
# Creates project specific library and renv.lock file. 
# Use 'renv::init(filepath)' to create project library
# renv::init(
#        "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains/R"
#    )

# Define project directory - contains the R scripts, data and result folders
project.dir <-
  file.path(
    "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains"
  )

# renv::snapshot(file.path(project.dir, "R"))

#renv::restore completed 24.09.2025
#renv::restore(file.path(project.dir, "R"))

```


# 2.1.1 Install,load essential functions and libraries

```{r load_essential_functions_current_session}

## Load all R scripts from the 'functions' folder into the current session
P2_functions <- sapply(list.files(file.path(project.dir, "R/functions"), pattern="*.R", full.names = TRUE), source)

## Install private package 
# Install ptm.stiochiometry package
#install.packages("/fast/AG_Sugimoto/home/users/pallavi/projects/ptm.stoichiometry", repos = NULL, type = "source")

# Load Libraries - ptm.stiochiometry and readxl
library(ptm.stoichiometry)
library("readxl")

```

```{r data_directories}

# Define path to data directory
data.dir <- file.path(project.dir, "data")
results.dir <- file.path(project.dir, "results")

```

# 2.1.2 Import human protein reference data 

```{r import_data, warning=FALSE}

# Import human protein reference data from specified file path 
ref_protein_data <- import_reference_fasta(file.path
                                           ("/fast/AG_Sugimoto/reference/uniprot/human", 
                                             "UP000005640_9606.fasta")) 

all.protein.bs <- Biostrings::readAAStringSet(
  file.path(
    "/fast/AG_Sugimoto/reference/uniprot/human",
    "UP000005640_9606.fasta"
  )
)

```


# 2.1.3 Calculation of Stoichiometry without diagnostic ion consideration 

```{r data_directory_wo_di}

# Load data into environment
pnas2022_data <- file.path(
  project.dir,
  "data/MQ_standard/PNAS2022" 
)

# Load sample info data 
MQ_standard_data <- read_excel(
  file.path(project.dir, "data/analysis_setting/PXD031221_sample_matrix.xlsx"),
  sheet = "MQ_standard"
) %>% data.table

# Add a new column 'sample_id' that assigns a unique sequential number to each row (1:N), 
#where N is the total number of rows in the data.table
MQ_standard_data[, sample_id := 1:.N]

```

```{r calculate_stoichiometry_wo_di}

## Stoichiomtery analysis using with MULTI-MSMS with 
# MULTI-SECPEP (secondary peptide) and MULTI-MSMS only

# Automate stoichiometry calculations across MaxQuant datasets (MULTI-MSMS + 
# MULTI-SECPEP and MULTI-MSMS only)
process_stoichiometry <- function(MQ_standard_data,
                                  output_dir,
                                  ref_protein_data,
                                  ptm_mapping_file,
                                  selected_type = NA,
                                  prefix_label = "") {
  
  # Create output directory if it does not already exist 
  dir.create(output_dir, recursive = TRUE, showWarnings = FALSE)
  
  # For each sample_id in the MQ_standard data, calculate the stoichiometry
  for (i in seq_len(nrow(MQ_standard_data))) {
    prefix    <- MQ_standard_data$prefix[i] # Extract the prefix column
    MQ_standard_sample <- MQ_standard_data$data[i] # Extract the data column 
    
    # Define file path to MaxQuant evidence files
    mq_evidence_data <- file.path(pnas2022_data, 
                                  "evidence", 
                                  paste0(prefix, "evidence.txt"))
    
    # Print which sample id is being processed
    message("Processing: ", basename(mq_evidence_data)) 
    
    
    # Checks whether the sample ID has the corresponding evidence.txt file. If yes, then proceed
    if (file.exists(mq_evidence_data)) {
      
      # Define corresponding sample information (metadata) file
      sample_info_file <- file.path(
        pnas2022_data, "sample_info",
        paste0("MS_dataset_overview_PXD031221_", MQ_standard_sample, ".csv")
      )
      
      # Define output prefix for results
      output_prefix <- file.path(output_dir, paste0(prefix_label, prefix))
      
      # Run main stoichiometry calculation
      calculate_stoichiometry(
        mq_evidence_data = mq_evidence_data,
        sample_info_file = sample_info_file,
        ref_protein_dt   = ref_protein_data,
        output_prefix    = output_prefix,
        ptm_mapping_file = ptm_mapping_file,
        K_only           = FALSE,
        selected_type    = selected_type
      )
      
    } else {
      # If evidence.txt does not exist, skip the function and print below message
      message("File does not exist: ", mq_evidence_data)
    }
    # Garbage collection - to free up memory 
    gc()
  }
}


# Define file path common PTM mapping file
ptm_mapping_file <- file.path(
  project.dir,
  "data/analysis_setting/ptm_replacement_de-propionylate_for_hydroxylysine.csv"
)

## MSMS + SECEP

# Subset data-A and data-D from MQ_standard_data
samples_to_process <- MQ_standard_data[data %in% c("data-A", "data-D")]

# Define output directory for MSMS + SECPEP results
MQ_Std_MSMS_SECEP_dir <- file.path(project.dir, "results", "p2-analysis-setting","MQ_Std_MSMS_SECEP")

# Run stoichiometry processing for MSMS + SECPEP
process_stoichiometry(
  MQ_standard_data = samples_to_process,
  output_dir       = MQ_Std_MSMS_SECEP_dir,
  ref_protein_data = ref_protein_data,
  ptm_mapping_file = ptm_mapping_file,
  selected_type    = NA,
  prefix_label     = "including_SECPEP_"
)

##MSMS only

# Define output directory for MSMS-only results
MQ_Std_MSMS_dir <- file.path(project.dir, "results","p2-analysis-setting", "MQ_Std_MSMS")

# Run stoichiometry processing for MSMS-only
process_stoichiometry(
  MQ_standard_data = MQ_standard_data,
  output_dir       = MQ_Std_MSMS_dir,
  ref_protein_data = ref_protein_data,
  ptm_mapping_file = ptm_mapping_file,
  selected_type    = c("MULTI-MSMS"),
  prefix_label     = ""
)
```


# 2.1.4 Calculation of Stiochiometry with diagnostic ions

```{r data_directory_w_di}

# Load data into environment
MQ_DI_data <- file.path(
  project.dir,
  "data/MQ_with_DI/PNAS2022" 
)

# Load sample run info data 
MQ_DI_run_info <- read_excel(
  file.path(project.dir, "data/analysis_setting/PXD031221_sample_matrix.xlsx"),
  sheet = "MQ_with_DI" 
) %>% data.table

# Add a new column 'sample_id' that assigns a unique sequential number to each 
#row (1:N), where N is the total number of rows in the data.table
MQ_DI_run_info[, sample_id := 1:.N]

# Create file path for results
MQ_with_DI_dir <- file.path(project.dir, "results", "p2-analysis-setting", "MQ_DI")
#dir.create(MQ_with_DI_dir, recursive = TRUE)

# Load common PTM mapping file
ptm_mapping_file <- file.path(
  project.dir,
  "data/analysis_setting/ptm_replacement_de-propionylate_for_hydroxylysine.csv"
)

```


```{r calculate_stoichiometry_w_di}

# For each sample ID calculate the stoichiomtery
for (i in seq_len(nrow(MQ_DI_run_info))){ # Takes each row from the MQ_DI_run_info
  
  prefix <- MQ_DI_run_info$prefix[i]
  
  # Retrieves the evidence.txt file for each sample ID 
  mq_evidence_data = file.path(MQ_DI_data,
                               "evidence",
                               paste0(prefix, "evidence.txt"))
  
  print(paste0("Processing: ", basename(mq_evidence_data)))
  
  # Checks whether the sample ID has the corresponding evidence.txt file. If yes, then proceed
  if (file.exists(mq_evidence_data)) { 
    
    # Locate and fetch all PTM site files within the ptm folder
    ptm_files <- list.files(file.path(
      MQ_DI_data, "ptm",
      paste0(MQ_DI_run_info[i, prefix], "ptm")), 
      full.names = TRUE)
    
    # Generate PTM names based on file names, add brackets and remove "Sites.txt"
    ptm_names <- paste0(
      "[", str_replace_all(basename(ptm_files), "Sites.txt", ""), "]"
    )
    
    # Run the stoichiometry calculation 
    stoic.dt <- calculate_stoichiometry2(
      mq_evidence_data = mq_evidence_data,
      sample_info_file = file.path( # Corresponding sample info data 
        MQ_DI_data,
        "sample_info",
        paste0(
          "MS_dataset_overview_PXD031221_",
          MQ_DI_run_info[i, data],
          ".csv"
        )
      ),
      ref_protein_dt = ref_protein_data,
      ptm_files = ptm_files,
      ptm_names = ptm_names,
      output_prefix = file.path(MQ_with_DI_dir,  # Define output prefix for results
                                paste0("DI_", MQ_DI_run_info[i, prefix])),
      ptm_mapping_file = ptm_mapping_file,
      K_only = FALSE,
      selected_type = c("MULTI-MSMS"),
    )
    # If evidence.txt does not exist, skip the function and print below message
  } else {
    print(paste0("File does not exist: ", mq_evidence_data))
  }
  
  
  gc()
  
}

```


# Session information

```{r sessionInfo}

sessioninfo::session_info()

```
