---
title: "2-5. Lysine hydroxylations in hypoxia and normoxia"
author: "Yoichiro Sugimoto and Pallavi Kesavan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   github_document:
     toc: yes
     toc_depth: 2
---

# Environment setup

```{r setup_environment}

## Initialize renv (first time only) - re-installed 24.09.2025
# Creates project specific library and renv.lock file. 
# Use 'renv::init(filepath)' to create project library
# renv::init(
#        "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains/R"
#    )

# Define project directory - contains the R scripts, data and result folders
 project.dir <-
  file.path(
    "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains"
)

# renv::snapshot(file.path(project.dir, "R"))

#renv::restore completed 24.09.2025
#renv::restore(file.path(project.dir, "R"))

```


# 2.5.1 Install,load essential functions and libraries

```{r load_essential_functions_current_session}

## Load all R scripts from the 'functions' folder into the current session
P2_functions <- sapply(list.files(file.path(project.dir, "R/functions"), pattern="*.R", full.names = TRUE), source)

## Install private package 
# Install ptm.stiochiometry package
#install.packages("/fast/AG_Sugimoto/home/users/pallavi/projects/ptm.stoichiometry", repos = NULL, type = "source")

# Load Libraries
library("readxl")
library("janitor")
library("ptm.stoichiometry")

```


# 2.5.2 Import human protein reference data 

```{r import_data, warning=FALSE}

# Import human protein reference data from specified file path 
ref_protein_dt <- import_reference_fasta(file.path
("/fast/AG_Sugimoto/reference/uniprot/human", 
  "UP000005640_9606.fasta")) 

```

# 2.5.3 Calculation of Stoichiometry with diagnostic ion in hypoxia and normoxia 

```{r data_directory_MS_KR_1}

# Define path to data directory
data.dir <- file.path(project.dir, "data")
results.dir <- file.path(project.dir, "results")

# Load data into environment
MS_KR1_data <- file.path(
  project.dir,
  "data/MQ_with_DI/MS_KR_1" 
)

# Create file path for results
MS_KR_1_dir <- file.path(project.dir, "results", "p2-analysis-setting", "MS_KR_1")
dir.create(MS_KR_1_dir, recursive = TRUE)

# Define file path common PTM mapping file
ptm_mapping_file <- file.path(
  project.dir,
  "data/analysis_setting/ptm_replacement_de-propionylate_for_hydroxylysine.csv"
)
```


```{r calculate_stoichiometry_MS_KR_1}
  
    # Define file path to MaxQuant evidence files
    mq_evidence_data <- file.path(MS_KR1_data, 
                                  "MS_KR_1_evidence.txt")
    
    # Print which sample id is being processed
    message("Processing: ", basename(mq_evidence_data)) 
    
   # Checks whether the sample ID has the corresponding evidence.txt file. If yes, then proceed
  if (file.exists(mq_evidence_data)) {
    
    # Locate and fetch all PTM site files within the ptm folder
    ptm_files <- list.files(file.path(
      MS_KR1_data, "ptm"), 
      full.names = TRUE)
    
    # Generate PTM names based on file names, add brackets and remove "Sites.txt"
    ptm_names <- paste0(
      "[", str_replace_all(basename(ptm_files), "Sites.txt", ""), "]"
    )
    
    # Run the stoichiometry calculation
    stoic.dt <- calculate_stoichiometry2(
      mq_evidence_data = mq_evidence_data,
      sample_info_file = file.path(
        MS_KR1_data,
        "sample_info.csv"
      ),
      ref_protein_dt = ref_protein_dt,
      ptm_files = ptm_files,
      ptm_names = ptm_names,
      output_prefix = file.path(MS_KR_1_dir, "MS_KR_1_"),
      ptm_mapping_file = ptm_mapping_file,
      K_only = FALSE,
      selected_type = "MULTI-MSMS",
      parse_protein_accession_function = NA
    )
  } else { # If evidence.txt does not exist, skip the function and print below message
    print(paste0("File does not exist: ", mq_evidence_data))
  }
  
  # Garbage collection - to free up memory
  gc()
  

```


```{r hydroxylation_hypoxia_vs_normoxia}

# Define function - 'read_stoic_data'
read_stoic_data <- function(prefix, pre_prefix, post_fix = "", dir_path){
  # Read csv file with defined file path,  
  dt <- fread(file.path(dir_path, paste0(pre_prefix, prefix, "PTM_stoichiometry", post_fix, ".csv"))) 
  dt[, condition := gsub("_$", "", prefix)] # Removes '_' at the end of the prefix and creates a new column called condiiton
  return(dt)
}

## Read stoichiometry data for MS_KR1 data 
MS_KR1_stoic_dt <- read_stoic_data(
  prefix = "MS_KR_1_",
  pre_prefix = "",
  post_fix = "_DI",
  dir_path = file.path(results.dir, "p2-analysis-setting", "MS_KR_1"))


#Filter data table with presence of diagnostic_peak and WT stoichiometry values
MS_KR1_stoic_dt[, `:=`(
  is_diagnostic_peak = diagnostic_peak == "+" 
)]

all.protein.bs <- Biostrings::readAAStringSet(
  file.path(
    "/fast/AG_Sugimoto/reference/uniprot/human",
    "UP000005640_9606.fasta"
  )
)

MS_KR1_stoic_dt[, `:=`(
  Oxygen_levels = fcase(
    grepl("^HeLaWT_NA_N_NA", sample_name), "Normoxia_WT",
    grepl("^HeLaiJMJD6_noDox_N_NA", sample_name), "Normoxia_JMJD6KO",
    grepl("^HeLaiJMJD6_Dox_01O224h_N2h", sample_name), "Hypoxia_reox_2h",
    grepl("^HeLaiJMJD6_Dox_01O224h_N4h", sample_name), "Hypoxia_reox_4h", 
    grepl("^HeLaiJMJD6_Dox_01O224h_NA", sample_name), "Hypoxia", 
    grepl("^HeLaiJMJD6_Dox_N_NA", sample_name), "Normoxia_JMJD6KO_reexp", 
    default = NA_character_
  ) %>% factor(levels = c("Normoxia_WT", "Normoxia_JMJD6KO", "Normoxia_JMJD6KO_reexp", "Hypoxia", "Hypoxia_reox_2h", "Hypoxia_reox_4h"))
)]

MS_KR1_stoic_dt[, `:=`(
  sample_name =  
    factor(sample_name, levels = c("HeLaWT_NA_N_NA", "HeLaiJMJD6_noDox_N_NA", "HeLaiJMJD6_Dox_N_NA", "HeLaiJMJD6_Dox_01O224h_NA", "HeLaiJMJD6_Dox_01O224h_N2h", "HeLaiJMJD6_Dox_01O224h_N4h"))
)]


# BRD4 
plot_ptm_stoichiometry(
  MS_KR1_stoic_dt[sample_name %in% c("HeLaWT_NA_N_NA","HeLaiJMJD6_noDox_N_NA", "HeLaiJMJD6_Dox_N_NA", "HeLaiJMJD6_Dox_01O224h_NA")], accession = "O60885", plot_range = c(531, 581), all.protein.bs, sample_colors = NA,
  )
  
# BRD3
plot_ptm_stoichiometry(
  MS_KR1_stoic_dt[sample_name %in% c("HeLaWT_NA_N_NA","HeLaiJMJD6_noDox_N_NA", "HeLaiJMJD6_Dox_N_NA", "HeLaiJMJD6_Dox_01O224h_NA")], accession = "Q15059", plot_range = c(483, 533), all.protein.bs, sample_colors = NA
  )

# BRD2
plot_ptm_stoichiometry(
  MS_KR1_stoic_dt[sample_name %in% c("HeLaWT_NA_N_NA","HeLaiJMJD6_noDox_N_NA", "HeLaiJMJD6_Dox_N_NA", "HeLaiJMJD6_Dox_01O224h_NA")], accession = "P25440", plot_range = c(540, 590), all.protein.bs, sample_colors = NA
  )



MS_KR1_stoic_dt[, stoic_bin := case_when(
  stoichiometry < 0.10 ~ "low",
  between(stoichiometry, 0.10, 0.50) ~ "middle",
  stoichiometry > 0.50 ~ "high"
)]


# Plot 
ggplot(
  data = MS_KR1_stoic_dt[sample_name %in% c("HeLaiJMJD6_Dox_N_NA", "HeLaiJMJD6_Dox_01O224h_NA","HeLaiJMJD6_Dox_01O224h_N2h", "HeLaiJMJD6_Dox_01O224h_N4h") & diagnostic_peak == "+"],
  aes(
    x = Oxygen_levels,
    y = stoichiometry,
    color = gene_name
  )
) +
  geom_point() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))

ggplot(
  data = MS_KR1_stoic_dt[gene_name == "BRD4" & diagnostic_peak == "+" & aa_pos == 538],
  aes(
    x = Oxygen_levels,
    y = stoichiometry,
  )
) +
  geom_col(fill = "steelblue") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1))


```


# Session information

```{r sessionInfo}

sessioninfo::session_info()

```
