---
title: "2-6. Stoichiometry calculations without considering water loss"
author: "Yoichiro Sugimoto and Pallavi Kesavan"
date: "`r format(Sys.time(), '%d %B, %Y')`"
vignette: >
  %\VignetteIndexEntry{Bioconductor style for PDF documents}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
output:
   github_document:
     toc: yes
     toc_depth: 2
---

# This script calculates the stoichiometry for MQ data with diagnostic ions and no water loss

# Environment setup

```{r setup_environment}

## Initialize renv (first time only) - re-installed 24.09.2025
# Creates project specific library and renv.lock file. 
# Use 'renv::init(filepath)' to create project library
# renv::init(
#        "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains/R"
#    )

# Define project directory - contains the R scripts, data and result folders
project.dir <-
  file.path(
    "/fast/AG_Sugimoto/home/users/pallavi/projects/20241111_PTMs_in_lysine_rich_domains"
  )

# renv::snapshot(file.path(project.dir, "R"))

#renv::restore completed 24.09.2025
#renv::restore(file.path(project.dir, "R"))

```

# 2.6.1 Install,load essential functions and libraries

```{r load_essential_functions_current_session}

## Load all R scripts from the 'functions' folder into the current session
P2_functions <- sapply(list.files(file.path(project.dir, "R/functions"), pattern="*.R", full.names = TRUE), source)

## Install private package 
# Install ptm.stiochiometry package
#install.packages("/fast/AG_Sugimoto/home/users/pallavi/projects/ptm.stoichiometry", repos = NULL, type = "source")

# Load Libraries
library("readxl")
library("janitor")
library("ptm.stoichiometry")

```


# 2.6.2 Import human protein reference data 

```{r import_data, warning=FALSE}

# Import human protein reference data from specified file path 
ref_protein_dt <- import_reference_fasta(file.path
                                         ("/fast/AG_Sugimoto/reference/uniprot/human", 
                                           "UP000005640_9606.fasta")) 

```

# 2.6.3 Calculation of Stoichiometry of MQ_DI without waterloss 

```{r data_directory_w_di_no_H2O}

# Define path to data directory
data.dir <- file.path(project.dir, "data")
results.dir <- file.path(project.dir, "results")

# Define file path common PTM mapping file
ptm_mapping_file <- file.path(
  project.dir,
  "data/analysis_setting/ptm_replacement_de-propionylate_for_hydroxylysine.csv"
)

# Load data into environment
MQ_DI_noH2O_data <- file.path(
  project.dir,
  "data/MQ_with_DI_no_waterloss/PNAS2022" 
)

# Create file path for results
MQ_DI_noH2O_dir <- file.path(project.dir, "results", "p2-analysis-setting", "MQ_DI_noH2O")
# dir.create(MQ_DI_noH2O_dir, recursive = TRUE)


```


```{r sample_info_MQ_DI_no_H2O}

# Load sample run info data 
MQ_DI_noH2O_run_info <- read_excel(
  file.path(project.dir, "data/analysis_setting/PXD031221_sample_matrix.xlsx"),
  sheet = "MQ_with_DI_noH2O" 
) %>% data.table

# Add a new column 'sample_id' that assigns a unique sequential number to each 
#row (1:N), where N is the total number of rows in the data.table
MQ_DI_noH2O_run_info[, sample_id := 1:.N]

```


```{r calculate_stoichiometry_MQ_DI_no_H2O}

# For each sample ID calculate the stoichiomtery
for (i in seq_len(nrow(MQ_DI_noH2O_run_info))){ # Takes each row from the MQ_DI_noH2O_run_info
  
  prefix <- MQ_DI_noH2O_run_info$prefix[i]
  
  # Retrieves the evidence.txt file for each sample ID 
  mq_evidence_data = file.path(MQ_DI_noH2O_data,
                               "evidence",
                               paste0(prefix, "evidence.txt"))
  
  print(paste0("Processing: ", basename(mq_evidence_data)))
  
  # Checks whether the sample ID has the corresponding evidence.txt file. If yes, then proceed
  if (file.exists(mq_evidence_data)) { 
    
    # Locate and fetch all PTM site files within the ptm folder
    ptm_files <- list.files(file.path(
      MQ_DI_noH2O_data, "ptm",
      paste0(MQ_DI_noH2O_run_info[i, prefix], "ptm")), 
      full.names = TRUE)
    
    # Generate PTM names based on file names, add brackets and remove "Sites.txt"
    ptm_names <- paste0(
      "[", str_replace_all(basename(ptm_files), "Sites.txt", ""), "]"
    )
    
    # Run the stoichiometry calculation 
    stoic.dt <- calculate_stoichiometry2(
      mq_evidence_data = mq_evidence_data,
      sample_info_file = file.path( # Corresponding sample info data 
        MQ_DI_noH2O_data,
        "sample_info",
        paste0(
          "MS_dataset_overview_PXD031221_",
          MQ_DI_noH2O_run_info[i, data],
          ".csv"
        )
      ),
      ref_protein_dt = ref_protein_dt,
      ptm_files = ptm_files,
      ptm_names = ptm_names,
      output_prefix = file.path(MQ_DI_noH2O_dir,  # Define output prefix for results
                                paste0("DI_", "noH2O_", MQ_DI_noH2O_run_info[i, prefix])),
      ptm_mapping_file = ptm_mapping_file,
      K_only = FALSE,
      selected_type = c("MULTI-MSMS"),
    )
    # If evidence.txt does not exist, skip the function and print below message
  } else {
    print(paste0("File does not exist: ", mq_evidence_data))
  }
  
  
  gc()
  
}

```


# 2.5.3 Calculation of Stoichiometry with diagnostic ion in hypoxia and normoxia 

```{r data_directory_MS_KR_1_no_H2O}

# Load data into environment
MS_KR1_no_H2O_data <- file.path(
  project.dir,
  "data/MQ_with_DI_no_waterloss/MS_KR_1" 
)

# Create file path for results
MS_KR_1_noH2O_dir <- file.path(project.dir, "results", "p2-analysis-setting", "MS_KR_1_noH2O")
#dir.create(MS_KR_1_noH2O_dir, recursive = TRUE)

```


```{r calculate_stoichiometry_MS_KR_1_no_H2O}
  
# Define file path to MaxQuant evidence files
mq_evidence_data <- file.path(MS_KR1_no_H2O_data, 
                              "MS_KR_1_evidence.txt")

# Print which sample id is being processed
message("Processing: ", basename(mq_evidence_data)) 

# Checks whether the sample ID has the corresponding evidence.txt file. If yes, then proceed
if (file.exists(mq_evidence_data)) {
  
  # Locate and fetch all PTM site files within the ptm folder
  ptm_files <- list.files(file.path(
    MS_KR1_no_H2O_data, "ptm"), 
    full.names = TRUE)
  
  # Generate PTM names based on file names, add brackets and remove "Sites.txt"
  ptm_names <- paste0(
    "[", str_replace_all(basename(ptm_files), "Sites.txt", ""), "]"
  )
  
  # Run the stoichiometry calculation
  stoic.dt <- calculate_stoichiometry2(
    mq_evidence_data = mq_evidence_data,
    sample_info_file = file.path(
      MS_KR1_no_H2O_data,
      "sample_info.csv"
    ),
    ref_protein_dt = ref_protein_dt,
    ptm_files = ptm_files,
    ptm_names = ptm_names,
    output_prefix = file.path(MS_KR_1_noH2O_dir, paste0("MS_KR_1_", "noH2O_")),
    ptm_mapping_file = ptm_mapping_file,
    K_only = FALSE,
    selected_type = "MULTI-MSMS",
    parse_protein_accession_function = NA
  )
} else { # If evidence.txt does not exist, skip the function and print below message
  print(paste0("File does not exist: ", mq_evidence_data))
}

# Garbage collection - to free up memory
gc()

```

# Session information

```{r sessionInfo}

sessioninfo::session_info()

```

